### ISSUE TITLE
input lowpass filter is sample rate dependent

### ISSUE THREAD

**Issue by falkTX** [AidaDSP/aidadsp-lv2#14]
Looking at the code, I dont see how the low pass filter adjusts itself if running at different sample rates, the value being set (0.5 * a percentage) never takes into account the plugin sample rate.

An older version used LPF in Hz instead of %, and made use of sample rate, but that is gone now.
Can you explain please?

**Comment by MaxPayne86** [comment]
the frequency passed to the class is samplerate normalized. Since this low pass is a percentage of nyquist = samplerate / 2 we would have

PC_CO(self->in_lpf_pc_old) * samplerate / 2 * 1 / samplerate = PC_CO(self->in_lpf_pc_old) * 1 / 2

since this is not done once but also everytime I change the LPF frequency I've decided to simplify the operations but if you think it should be more clear I will revert with previous impl.

Note PC_CO(self->in_lpf_pc_old) would be a number between 0.25 and 1.00 according to the ttl

**Comment by falkTX** [comment]
The problem is that the sample rate is never passed when dealing with the LPF.

during init we have:

```
    self->in_lpf_pc_old = 50.0f;
    self->in_lpf = new Biquad(bq_type_lowpass, PC_CO(self->in_lpf_pc_old) * 0.5f, 0.707f, 0.0f);
```

note no sample rate involed here.

when LPF is changed by the user, we have:

```
    if (in_lpf_pc != self->in_lpf_pc_old) { /* Update filter coeffs */
        self->in_lpf->setBiquad(bq_type_lowpass, PC_CO(in_lpf_pc) * 0.5f, 0.707f, 0.0f);
        self->in_lpf_pc_old = in_lpf_pc;
    }
```

note how there is no samplerate involved there either.

so something is obviously wrong, how is the filter supposed to know the active sample rate if we never tell it?

**Comment by falkTX** [comment]
to be honest I am not really following.
but DSP has never been my thing, if you are confident this filter stuff works in any sampling rate as-is, that is good to me :)
feel free to close in that case.

**Comment by MaxPayne86** [comment]
No pb we will eventually re-discuss again by voice closing for now
