### ISSUE TITLE
Is model input gain needed?

### ISSUE THREAD

**Issue by falkTX** [AidaDSP/aidadsp-lv2#26]
I dont think this is strictly necessary, and might be confusing for users training the models.

For the output we already have gain compensation values, I will send you a PR soon.

**Comment by MaxPayne86** [comment]
okay for the PR, for the input gain Sebastian asked this since the default value for pregain could not be correct for certain types of amps, and the "average default" input level of the guitar at least for the Dwarf could be too high or too low for a certain amp model to sound in the sweet spot. Please @spunktsch provide additional info if needed.

**Comment by spunktsch** [comment]
as @MaxPayne86 explained main reason for that is to have the same amount of gain from the model as expected with the real amp. This is to be done after training by the one who trained the amp and know how much is missing.

**Comment by falkTX** [comment]
fair enough, then I say we just need to document this somewhere. but leaving that up to you
