### ISSUE TITLE
INLPF param generates clicks when changed and noise at 100%

### ISSUE THREAD

**Issue by jesseverhage** [AidaDSP/aidadsp-lv2#27]
Found a small issue with the INLPF parameter on the AIDA-X, when you turn it to its max value and then back, it generates a rather nasty click. The click is easier to spot when using the scrollwheel to set the value to max and back.

On top of that, if you set it to the max value and leave it there for a while the plugin will start to generate an odd noise that I have a hard time describing.

I suspect the parameter to be broken. As its name is INLPF, I assume it should be a low pass filter applied to the input signal. However, it doesnt seem to impact the sound at all here, except when it is set to 100%.

Tested on: MOD Dwarf, firmware v1.13.1, with Sunhead Clean Jazz neural model and IR file

**Comment by MaxPayne86** [comment]
@jesseverhage was indeed an interesting digital filters theory thing! This filter is a LPF on the input of the amp and is there since we can fool around with Neural Networks all the time but Aliasing is a beast and is still pretty much there. So it is conceived as an anti-aliasing filter. Which should come into play if expecially extreme high gain settings one could notice some aliasing effect happening. The control spans from Nyquist Freq / 4 to Nyquist Freq. And THAT was the problem. You can't set the corner frequency of a digital filter to be EXACTLY the Nyquist Frequency or weird things will happen. I've fixed now into 3fd2c98a3c35c6b4a833c617362c6206fd96d379. Note: the real anti-aliasing solution would be oversampling, but at the moment this solution would consume too much cpu on an embedded device.
