### ISSUE TITLE
BUG: 2 instances of the plugin

### ISSUE THREAD

**Issue by spunktsch** [AidaDSP/aidadsp-lv2#9]
the main output gets distorted as soon as you add a second instance of the plugin.

**Comment by falkTX** [comment]
I can reproduce oddities with 2 instances, where the 2nd instance gets crackling sound while the 1st instance is still fine.

the bad sound mostly goes away on the 2nd instance when deleting the 1st.
adding another instance and connecting something into it brings the issue back again.

seems that we can keep 2 instances running mostly fine, but feeding audio to multiple instances generates noise. (which makes the whole thing pointless)

if we connect 2 instances in series, the bad noise goes away.
this makes me think the issue is running multiple plugins in parallel, as done with mod-host with jack2.

**Comment by MaxPayne86** [comment]
@falkTX thanks, what if you remove the mutex (i.e. to replicate the issue) but you disable neural network processing with the apposite switch in one of the two plugins? My Dwarf is arriving tomorrow. I cannot replicate on my setup (derivative Mod).

**Comment by falkTX** [comment]
I will keep making some tests. seems that using 256 frames also works around the issue.
